### 1) Basic Array Creation 🍏

Create a 1D NumPy array containing the integers from 10 to 50, inclusive

<details><summary>Useful functions</summary>

```python
numpy.arange(start, stop, step)  # Returns an array of evenly spaced values within a given interval.
```
</details>

In [1]:
import numpy as np

arr = np.arange(10, 51)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


### 2) Array Arithmetic 🔢

Create two NumPy arrays of shape `(3, 3)`, filled with random integers between 1 and 20

Perform element-wise addition, subtraction, multiplication, and division

<details><summary>Useful functions</summary>

```python
numpy.random.randint(low, high, size)  # Returns an array of random integers from low (inclusive) to high (exclusive)
```
</details>

In [2]:
arr1 = np.random.randint(1, 21, size=(3, 3))
arr2 = np.random.randint(1, 21, size=(3, 3))

addition = arr1 + arr2
subtraction = arr1 - arr2
multiplication = arr1 * arr2
division = arr1 / arr2

print("Addition:\n", addition)
print("Subtraction:\n", subtraction)
print("Multiplication:\n", multiplication)
print("Division:\n", division)

Addition:
 [[16  6 11]
 [31 13 27]
 [24 28 18]]
Subtraction:
 [[ -8   0   5]
 [ -7  -5  -3]
 [-12  -6 -12]]
Multiplication:
 [[ 48   9  24]
 [228  36 180]
 [108 187  45]]
Division:
 [[0.33333333 1.         2.66666667]
 [0.63157895 0.44444444 0.8       ]
 [0.33333333 0.64705882 0.2       ]]


### 3) Summing the Diagonals 🎲

Create a 5x5 matrix of random integers between 10 and 100

Calculate the sum of both the main diagonal and the anti-diagonal

<details><summary>Useful functions</summary>

```python
numpy.diag(array)    # Extracts the diagonal elements of an array
numpy.fliplr(array)  # Flips the array in the left/right direction
numpy.sum(array)     # Returns the sum of all elements in the array
```
</details>

In [3]:
matrix = np.random.randint(10, 101, size=(5, 5))

main_diag_sum = np.sum(np.diag(matrix))
anti_diag_sum = np.sum(np.diag(np.fliplr(matrix)))

print("Main diagonal sum:", main_diag_sum)
print("Anti-diagonal sum:", anti_diag_sum)

Main diagonal sum: 247
Anti-diagonal sum: 347


### 4) Fancy Indexing with Conditions 🔍

Generate a NumPy array of 100 random integers between 1 and 100

Find all elements that are divisible by 3 but not by 5 using array indexing

In [4]:
arr = np.random.randint(1, 101, size=100)

filtered = arr[(arr % 3 == 0) & (arr % 5 != 0)]

print(filtered)

[27 81 39 12 51 27 96  9 33 12 54 21 51 57 42 99 51 18 93 66  6  3]


### 5) Flatten, Sort, and Find 📏

Create a 6x6 matrix of random integers

Flatten it into a 1D array, sort the array, and find the 3 largest elements

<details><summary>Useful functions</summary>

```python
numpy.ndarray.ravel(array)  # Returns a flattened array
numpy.sort(array)           # Returns a sorted copy of the array
```
</details>

In [5]:
matrix = np.random.randint(1, 101, size=(6, 6))

flattened = matrix.ravel()
sorted_array = np.sort(flattened)
largest_3 = sorted_array[-3:]

print("3 largest elements:", largest_3)

3 largest elements: [99 99 99]


### 6) Normalize the Data 📈

Create a NumPy array with 20 random floating-point numbers between 0 and 1

Normalize this data so that the new values range between 0 and 100

> *Hint:* The formula for normalization is: $X_{\text{norm}} = \frac{X - X_{\text{min}}}{X_{\text{max}} - X_{\text{min}}} \times (\text{new-max} - \text{new-min}) + \text{new-min}$

<details><summary>Useful functions</summary>

```python
numpy.random.rand(size)  # Returns an array of random floats in the half-open interval [0.0, 1.0)
```
</details>

In [6]:
arr = np.random.rand(20)

normalized = (arr - arr.min()) / (arr.max() - arr.min()) * (100 - 0) + 0

print("Normalized array:", normalized)

Normalized array: [ 65.80072545  76.31587023  18.72842322  84.46764364  34.89471042
  57.87302605  47.41036145  34.33265447   6.26482588   0.
  89.90493604  54.71418158  90.46089926  54.95916868  32.56289898
  97.80895191  99.86492151 100.          34.05500722  47.74259213]


### 7) Broadcasting and Scaling 📊

Create a 4x5 matrix of random integers between 10 and 100

Subtract the column-wise mean from each element in the matrix

<details><summary>Useful functions</summary>

```python
numpy.ndarray.mean(array, axis)  # Returns the mean of the array along the specified axis
```
</details>

In [7]:
matrix = np.random.randint(10, 101, size=(4, 5))

column_means = matrix.mean(axis=0)
standardized = matrix - column_means

print("Column-wise mean subtracted:\n", standardized)

Column-wise mean subtracted:
 [[-24.5 -14.   -9.  -33.  -47. ]
 [ 23.5 -16.  -28.   23.  -19. ]
 [ 14.5  38.   44.    0.   32. ]
 [-13.5  -8.   -7.   10.   34. ]]


### 8) Matrix Multiplication Challenge 🤯

Create two matrices of size 4x3 and 3x5 with random integers

Perform matrix multiplication on them

<details><summary>Useful functions</summary>

```python
numpy.ndarray.dot(array1, array2)  # Returns the dot product of two arrays
```
</details>

In [8]:
matrix1 = np.random.randint(1, 10, size=(4, 3))
matrix2 = np.random.randint(1, 10, size=(3, 5))

result = np.dot(matrix1, matrix2)

print("Matrix multiplication result:\n", result)

Matrix multiplication result:
 [[ 77  65  57  40  27]
 [185 163 150 111  58]
 [106  88  78  50  30]
 [ 60  51  45  32  21]]


### 9) Find the Peaks 📉

Generate a 1D NumPy array with 20 random integers between 0 and 50

Identify the "peaks" (local maxima) in the array (local maxima)

> *Hint:* compare each element to its neighbors

In [9]:
arr = np.random.randint(0, 51, size=20)

peaks = arr[1:-1][(arr[1:-1] > arr[:-2]) & (arr[1:-1] > arr[2:])]

print("Peaks:", peaks)

Peaks: [40 49 33 30 37 20 48 10]


### 10) Simulate a Dice Roll 🎲🎲

Simulate rolling two six-sided dice 10,000 times

Count how many times the sum of the two dice equals 7

In [10]:
rolls = np.random.randint(1, 7, size=(10000, 2))

sums = rolls.sum(axis=1)
sevens = np.sum(sums == 7)

print("Number of times the sum is 7:", sevens)

Number of times the sum is 7: 1642
